import { ThemeProvider } from "@/components/theme-provider"
import type { Metadata } from "next";
import { Sidebar, SidebarBody, SidebarLinks } from '@/components/aceternity/sidebar'
import localFont from 'next/font/local'
import Link from "next/link"
import "./globals.css";
import { X } from "lucide-react";
import { ModeToggle } from "@/components/ui/mode-toggle";
import { Button } from "@/components/ui/button";

const Sohne = localFont({
  src: [
    {
      path: './fonts/soehne-buch.woff2',
      weight: '400',
      style: 'normal',

    },
    {
      path: './fonts/soehne-kraftig.woff2',
      weight: '500',
      style: 'normal'
    }
  ],
  variable: '--font-sohne',
})

const Plantijn = localFont({
  src: [{
    path: './fonts/martina-plantijn-italic.woff2',
    weight: '400',
    style: 'italic'
  }],
  variable: '--font-plantijn',
})

export const metadata: Metadata = {
  title: "Andre Souza",
  description: "Generated by create next app",
}

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${Sohne.variable} ${Plantijn.variable} ${"flex bg-background md:bg-sidebar flex-col md:flex-row"}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Sidebar animate={false}>
            <SidebarBody>
              <div className="flex h-14 items-center justify-between">
                <Button variant="outline" size="icon" className="md:hidden">
                  <X className="h-[1.2rem] w-[1.2rem] rotate-0 scale-100" />
                </Button>
                <Link href="/" className="flex items-center gap-2.5 pr-3 font-medium">
                  <Button size="icon" className="bg-sidebar-active hover:bg-sidebar-hover" >
                    <svg width="20" height="20" viewBox="0 0 92 92" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path fillRule="evenodd" clipRule="evenodd" d="M26.509 31.1871C21.1742 20.5301 25.5236 7.58353 36.2235 2.27013C46.9234 -3.04327 59.9222 1.2886 65.257 11.9456L89.7207 60.8156C95.0555 71.4726 90.7062 84.4192 80.0063 89.7326C69.3063 95.046 56.3076 90.7141 50.9728 80.0571L26.509 31.1871ZM60.99 21.0655C60.99 29.2917 54.2945 35.9604 46.0351 35.9604C37.7757 35.9604 31.0801 29.2917 31.0801 21.0655C31.0801 12.8392 37.7757 6.17048 46.0351 6.17048C54.2945 6.17048 60.99 12.8392 60.99 21.0655ZM2.27927 60.8157L15.1891 35.0264L39.1086 83.1406L39.1453 83.1458C33.0386 91.5044 21.5914 94.4987 11.9937 89.7327C1.29379 84.4193 -3.05552 71.4727 2.27927 60.8157Z" fill="#1f1f23" className="dark:fill-white" />
                    </svg>
                  </Button>
                  <div className="flex flex-col">
                    <span className="text-[14px] leading-tight font-medium">Andre Souza</span>
                    <span className="text-[12px] leading-tight text-muted-foreground font-normal">andregsweb@gmail.com</span>
                  </div>
                </Link>
                <ModeToggle />
              </div>
              <section>
                <SidebarLinks />
              </section>
            </SidebarBody>
          </Sidebar>
          <main className="h-full m-0 flex flex-col w-full bg-background m-0 md:m-2 md:h-[calc(100svh_-_1rem)] sm:rounded-lg overflow-auto shadow-md">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html >
  );
}